services:
  redis-core:
    image: redis:7.2-alpine
    container_name: neticket-dev-redis-core
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data/core:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-queue:
    image: redis:7.2-alpine
    container_name: neticket-dev-redis-queue
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data/queue:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
