export const API_ERROR_CODES = {
  KOPIS_SYNC_FAILED: "KOPIS_SYNC_FAILED",
  KOPIS_INVALID_DATE_RANGE: "KOPIS_INVALID_DATE_RANGE",
  CHAT_NICKNAME_DUPLICATE: "CHAT_NICKNAME_DUPLICATE",
  CHAT_NICKNAME_REQUIRED: "CHAT_NICKNAME_REQUIRED",
  PERFORMANCE_NOT_FOUND: "PERFORMANCE_NOT_FOUND",
  VENUE_NOT_FOUND: "VENUE_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  BLOCK_GRADE_ALREADY_ASSIGNED: "BLOCK_GRADE_ALREADY_ASSIGNED",
  BLOCK_NAME_DUPLICATE: "BLOCK_NAME_DUPLICATE",
} as const;

export const TICKET_ERROR_CODES = {
  TICKETING_NOT_OPEN: "TICKETING_NOT_OPEN",
  INVALID_SEAT_COORDINATES: "INVALID_SEAT_COORDINATES",
  DUPLICATE_SEATS: "DUPLICATE_SEATS",
  SEATS_ALREADY_RESERVED: "SEATS_ALREADY_RESERVED",
  INVALID_BLOCK_FOR_SESSION: "INVALID_BLOCK_FOR_SESSION",
  BLOCK_DATA_NOT_FOUND: "BLOCK_DATA_NOT_FOUND",
  CAPTCHA_PARAMS_REQUIRED: "CAPTCHA_PARAMS_REQUIRED",
  NO_PERFORMANCES_FOUND: "NO_PERFORMANCES_FOUND",
  NO_SESSIONS_FOUND: "NO_SESSIONS_FOUND",
  NO_BLOCKS_FOUND: "NO_BLOCKS_FOUND",
  VIRTUAL_USER_PROCESS_FAILED: "VIRTUAL_USER_PROCESS_FAILED",
  VIRTUAL_USER_RELEASE_FAILED: "VIRTUAL_USER_RELEASE_FAILED",
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_TOKEN_TYPE: "INVALID_TOKEN_TYPE",
  INVALID_TOKEN_PAYLOAD: "INVALID_TOKEN_PAYLOAD",
  USER_NOT_ACTIVE: "USER_NOT_ACTIVE",
  ACTIVE_TOKEN_EXPIRED: "ACTIVE_TOKEN_EXPIRED",
  INVALID_ACTIVE_TOKEN: "INVALID_ACTIVE_TOKEN",
  ACTIVE_TOKEN_REQUIRED: "ACTIVE_TOKEN_REQUIRED",
} as const;

export const QUEUE_ERROR_CODES = {
  QUEUE_TICKETING_NOT_OPEN: "QUEUE_TICKETING_NOT_OPEN",
  QUEUE_CONFIG_SEED_FAILED: "QUEUE_CONFIG_SEED_FAILED",
  QUEUE_HEARTBEAT_UPDATE_FAILED: "QUEUE_HEARTBEAT_UPDATE_FAILED",
  QUEUE_TRANSFER_FAILED: "QUEUE_TRANSFER_FAILED",
  QUEUE_REMOVE_ACTIVE_FAILED: "QUEUE_REMOVE_ACTIVE_FAILED",
  QUEUE_TRIGGER_FAILED: "QUEUE_TRIGGER_FAILED",
  QUEUE_DONE_EVENT_FAILED: "QUEUE_DONE_EVENT_FAILED",
  QUEUE_VIRTUAL_INJECT_FAILED: "QUEUE_VIRTUAL_INJECT_FAILED",
  QUEUE_INJECTION_START_FAILED: "QUEUE_INJECTION_START_FAILED",
} as const;
